/* DO NOT EDIT: This file is automatically generated by Cabal */

/* package ceph-0.0.1 */
#ifndef VERSION_ceph
#define VERSION_ceph "0.0.1"
#endif /* VERSION_ceph */
#ifndef MIN_VERSION_ceph
#define MIN_VERSION_ceph(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  0 || \
  (major1) == 0 && (major2) == 0 && (minor) <= 1)
#endif /* MIN_VERSION_ceph */

/* package Euterpea-2.0.7 */
#ifndef VERSION_Euterpea
#define VERSION_Euterpea "2.0.7"
#endif /* VERSION_Euterpea */
#ifndef MIN_VERSION_Euterpea
#define MIN_VERSION_Euterpea(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  0 || \
  (major1) == 2 && (major2) == 0 && (minor) <= 7)
#endif /* MIN_VERSION_Euterpea */

/* package HCodecs-0.5.1 */
#ifndef VERSION_HCodecs
#define VERSION_HCodecs "0.5.1"
#endif /* VERSION_HCodecs */
#ifndef MIN_VERSION_HCodecs
#define MIN_VERSION_HCodecs(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  5 || \
  (major1) == 0 && (major2) == 5 && (minor) <= 1)
#endif /* MIN_VERSION_HCodecs */

/* package StateVar-1.1.1.1 */
#ifndef VERSION_StateVar
#define VERSION_StateVar "1.1.1.1"
#endif /* VERSION_StateVar */
#ifndef MIN_VERSION_StateVar
#define MIN_VERSION_StateVar(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  1 || \
  (major1) == 1 && (major2) == 1 && (minor) <= 1)
#endif /* MIN_VERSION_StateVar */

/* package adjunctions-4.4 */
#ifndef VERSION_adjunctions
#define VERSION_adjunctions "4.4"
#endif /* VERSION_adjunctions */
#ifndef MIN_VERSION_adjunctions
#define MIN_VERSION_adjunctions(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  4 || \
  (major1) == 4 && (major2) == 4 && (minor) <= 0)
#endif /* MIN_VERSION_adjunctions */

/* package aeson-1.4.4.0 */
#ifndef VERSION_aeson
#define VERSION_aeson "1.4.4.0"
#endif /* VERSION_aeson */
#ifndef MIN_VERSION_aeson
#define MIN_VERSION_aeson(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  4 || \
  (major1) == 1 && (major2) == 4 && (minor) <= 4)
#endif /* MIN_VERSION_aeson */

/* package apecs-0.7.1 */
#ifndef VERSION_apecs
#define VERSION_apecs "0.7.1"
#endif /* VERSION_apecs */
#ifndef MIN_VERSION_apecs
#define MIN_VERSION_apecs(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  7 || \
  (major1) == 0 && (major2) == 7 && (minor) <= 1)
#endif /* MIN_VERSION_apecs */

/* package base-4.12.0.0 */
#ifndef VERSION_base
#define VERSION_base "4.12.0.0"
#endif /* VERSION_base */
#ifndef MIN_VERSION_base
#define MIN_VERSION_base(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  12 || \
  (major1) == 4 && (major2) == 12 && (minor) <= 0)
#endif /* MIN_VERSION_base */

/* package bytestring-0.10.8.2 */
#ifndef VERSION_bytestring
#define VERSION_bytestring "0.10.8.2"
#endif /* VERSION_bytestring */
#ifndef MIN_VERSION_bytestring
#define MIN_VERSION_bytestring(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  10 || \
  (major1) == 0 && (major2) == 10 && (minor) <= 8)
#endif /* MIN_VERSION_bytestring */

/* package containers-0.5.11.0 */
#ifndef VERSION_containers
#define VERSION_containers "0.5.11.0"
#endif /* VERSION_containers */
#ifndef MIN_VERSION_containers
#define MIN_VERSION_containers(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  5 || \
  (major1) == 0 && (major2) == 5 && (minor) <= 11)
#endif /* MIN_VERSION_containers */

/* package contravariant-1.5.2 */
#ifndef VERSION_contravariant
#define VERSION_contravariant "1.5.2"
#endif /* VERSION_contravariant */
#ifndef MIN_VERSION_contravariant
#define MIN_VERSION_contravariant(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  5 || \
  (major1) == 1 && (major2) == 5 && (minor) <= 2)
#endif /* MIN_VERSION_contravariant */

/* package directory-1.3.3.0 */
#ifndef VERSION_directory
#define VERSION_directory "1.3.3.0"
#endif /* VERSION_directory */
#ifndef MIN_VERSION_directory
#define MIN_VERSION_directory(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  3 || \
  (major1) == 1 && (major2) == 3 && (minor) <= 3)
#endif /* MIN_VERSION_directory */

/* package distributive-0.6 */
#ifndef VERSION_distributive
#define VERSION_distributive "0.6"
#endif /* VERSION_distributive */
#ifndef MIN_VERSION_distributive
#define MIN_VERSION_distributive(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  6 || \
  (major1) == 0 && (major2) == 6 && (minor) <= 0)
#endif /* MIN_VERSION_distributive */

/* package first-class-families-0.5.0.0 */
#ifndef VERSION_first_class_families
#define VERSION_first_class_families "0.5.0.0"
#endif /* VERSION_first_class_families */
#ifndef MIN_VERSION_first_class_families
#define MIN_VERSION_first_class_families(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  5 || \
  (major1) == 0 && (major2) == 5 && (minor) <= 0)
#endif /* MIN_VERSION_first_class_families */

/* package gloss-1.13.0.1 */
#ifndef VERSION_gloss
#define VERSION_gloss "1.13.0.1"
#endif /* VERSION_gloss */
#ifndef MIN_VERSION_gloss
#define MIN_VERSION_gloss(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  13 || \
  (major1) == 1 && (major2) == 13 && (minor) <= 0)
#endif /* MIN_VERSION_gloss */

/* package groups-0.4.1.0 */
#ifndef VERSION_groups
#define VERSION_groups "0.4.1.0"
#endif /* VERSION_groups */
#ifndef MIN_VERSION_groups
#define MIN_VERSION_groups(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  4 || \
  (major1) == 0 && (major2) == 4 && (minor) <= 1)
#endif /* MIN_VERSION_groups */

/* package lens-4.17.1 */
#ifndef VERSION_lens
#define VERSION_lens "4.17.1"
#endif /* VERSION_lens */
#ifndef MIN_VERSION_lens
#define MIN_VERSION_lens(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  17 || \
  (major1) == 4 && (major2) == 17 && (minor) <= 1)
#endif /* MIN_VERSION_lens */

/* package linear-1.20.9 */
#ifndef VERSION_linear
#define VERSION_linear "1.20.9"
#endif /* VERSION_linear */
#ifndef MIN_VERSION_linear
#define MIN_VERSION_linear(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  20 || \
  (major1) == 1 && (major2) == 20 && (minor) <= 9)
#endif /* MIN_VERSION_linear */

/* package mtl-2.2.2 */
#ifndef VERSION_mtl
#define VERSION_mtl "2.2.2"
#endif /* VERSION_mtl */
#ifndef MIN_VERSION_mtl
#define MIN_VERSION_mtl(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  2 || \
  (major1) == 2 && (major2) == 2 && (minor) <= 2)
#endif /* MIN_VERSION_mtl */

/* package optparse-applicative-0.14.3.0 */
#ifndef VERSION_optparse_applicative
#define VERSION_optparse_applicative "0.14.3.0"
#endif /* VERSION_optparse_applicative */
#ifndef MIN_VERSION_optparse_applicative
#define MIN_VERSION_optparse_applicative(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  14 || \
  (major1) == 0 && (major2) == 14 && (minor) <= 3)
#endif /* MIN_VERSION_optparse_applicative */

/* package random-1.1 */
#ifndef VERSION_random
#define VERSION_random "1.1"
#endif /* VERSION_random */
#ifndef MIN_VERSION_random
#define MIN_VERSION_random(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  1 || \
  (major1) == 1 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_random */

/* package safe-0.3.17 */
#ifndef VERSION_safe
#define VERSION_safe "0.3.17"
#endif /* VERSION_safe */
#ifndef MIN_VERSION_safe
#define MIN_VERSION_safe(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  3 || \
  (major1) == 0 && (major2) == 3 && (minor) <= 17)
#endif /* MIN_VERSION_safe */

/* package safe-exceptions-0.1.7.0 */
#ifndef VERSION_safe_exceptions
#define VERSION_safe_exceptions "0.1.7.0"
#endif /* VERSION_safe_exceptions */
#ifndef MIN_VERSION_safe_exceptions
#define MIN_VERSION_safe_exceptions(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 7)
#endif /* MIN_VERSION_safe_exceptions */

/* package sdl2-2.4.1.0 */
#ifndef VERSION_sdl2
#define VERSION_sdl2 "2.4.1.0"
#endif /* VERSION_sdl2 */
#ifndef MIN_VERSION_sdl2
#define MIN_VERSION_sdl2(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  4 || \
  (major1) == 2 && (major2) == 4 && (minor) <= 1)
#endif /* MIN_VERSION_sdl2 */

/* package sdl2-mixer-1.1.0 */
#ifndef VERSION_sdl2_mixer
#define VERSION_sdl2_mixer "1.1.0"
#endif /* VERSION_sdl2_mixer */
#ifndef MIN_VERSION_sdl2_mixer
#define MIN_VERSION_sdl2_mixer(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  1 || \
  (major1) == 1 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_sdl2_mixer */

/* package sdl2-ttf-2.1.0 */
#ifndef VERSION_sdl2_ttf
#define VERSION_sdl2_ttf "2.1.0"
#endif /* VERSION_sdl2_ttf */
#ifndef MIN_VERSION_sdl2_ttf
#define MIN_VERSION_sdl2_ttf(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  1 || \
  (major1) == 2 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_sdl2_ttf */

/* package singletons-2.5.1 */
#ifndef VERSION_singletons
#define VERSION_singletons "2.5.1"
#endif /* VERSION_singletons */
#ifndef MIN_VERSION_singletons
#define MIN_VERSION_singletons(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  5 || \
  (major1) == 2 && (major2) == 5 && (minor) <= 1)
#endif /* MIN_VERSION_singletons */

/* package template-haskell-2.14.0.0 */
#ifndef VERSION_template_haskell
#define VERSION_template_haskell "2.14.0.0"
#endif /* VERSION_template_haskell */
#ifndef MIN_VERSION_template_haskell
#define MIN_VERSION_template_haskell(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  14 || \
  (major1) == 2 && (major2) == 14 && (minor) <= 0)
#endif /* MIN_VERSION_template_haskell */

/* package text-1.2.3.1 */
#ifndef VERSION_text
#define VERSION_text "1.2.3.1"
#endif /* VERSION_text */
#ifndef MIN_VERSION_text
#define MIN_VERSION_text(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  2 || \
  (major1) == 1 && (major2) == 2 && (minor) <= 3)
#endif /* MIN_VERSION_text */

/* package text-conversions-0.3.0 */
#ifndef VERSION_text_conversions
#define VERSION_text_conversions "0.3.0"
#endif /* VERSION_text_conversions */
#ifndef MIN_VERSION_text_conversions
#define MIN_VERSION_text_conversions(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  3 || \
  (major1) == 0 && (major2) == 3 && (minor) <= 0)
#endif /* MIN_VERSION_text_conversions */

/* package time-1.8.0.2 */
#ifndef VERSION_time
#define VERSION_time "1.8.0.2"
#endif /* VERSION_time */
#ifndef MIN_VERSION_time
#define MIN_VERSION_time(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  8 || \
  (major1) == 1 && (major2) == 8 && (minor) <= 0)
#endif /* MIN_VERSION_time */

/* package vector-0.12.0.3 */
#ifndef VERSION_vector
#define VERSION_vector "0.12.0.3"
#endif /* VERSION_vector */
#ifndef MIN_VERSION_vector
#define MIN_VERSION_vector(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  12 || \
  (major1) == 0 && (major2) == 12 && (minor) <= 0)
#endif /* MIN_VERSION_vector */

/* tool gcc-7.2.0 */
#ifndef TOOL_VERSION_gcc
#define TOOL_VERSION_gcc "7.2.0"
#endif /* TOOL_VERSION_gcc */
#ifndef MIN_TOOL_VERSION_gcc
#define MIN_TOOL_VERSION_gcc(major1,major2,minor) (\
  (major1) <  7 || \
  (major1) == 7 && (major2) <  2 || \
  (major1) == 7 && (major2) == 2 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_gcc */

/* tool ghc-8.6.5 */
#ifndef TOOL_VERSION_ghc
#define TOOL_VERSION_ghc "8.6.5"
#endif /* TOOL_VERSION_ghc */
#ifndef MIN_TOOL_VERSION_ghc
#define MIN_TOOL_VERSION_ghc(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  6 || \
  (major1) == 8 && (major2) == 6 && (minor) <= 5)
#endif /* MIN_TOOL_VERSION_ghc */

/* tool ghc-pkg-8.6.5 */
#ifndef TOOL_VERSION_ghc_pkg
#define TOOL_VERSION_ghc_pkg "8.6.5"
#endif /* TOOL_VERSION_ghc_pkg */
#ifndef MIN_TOOL_VERSION_ghc_pkg
#define MIN_TOOL_VERSION_ghc_pkg(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  6 || \
  (major1) == 8 && (major2) == 6 && (minor) <= 5)
#endif /* MIN_TOOL_VERSION_ghc_pkg */

/* tool haddock-2.22.0 */
#ifndef TOOL_VERSION_haddock
#define TOOL_VERSION_haddock "2.22.0"
#endif /* TOOL_VERSION_haddock */
#ifndef MIN_TOOL_VERSION_haddock
#define MIN_TOOL_VERSION_haddock(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  22 || \
  (major1) == 2 && (major2) == 22 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_haddock */

/* tool hpc-0.67 */
#ifndef TOOL_VERSION_hpc
#define TOOL_VERSION_hpc "0.67"
#endif /* TOOL_VERSION_hpc */
#ifndef MIN_TOOL_VERSION_hpc
#define MIN_TOOL_VERSION_hpc(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  67 || \
  (major1) == 0 && (major2) == 67 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_hpc */

/* tool hsc2hs-0.68.5 */
#ifndef TOOL_VERSION_hsc2hs
#define TOOL_VERSION_hsc2hs "0.68.5"
#endif /* TOOL_VERSION_hsc2hs */
#ifndef MIN_TOOL_VERSION_hsc2hs
#define MIN_TOOL_VERSION_hsc2hs(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 5)
#endif /* MIN_TOOL_VERSION_hsc2hs */

/* tool pkg-config-0.29.2 */
#ifndef TOOL_VERSION_pkg_config
#define TOOL_VERSION_pkg_config "0.29.2"
#endif /* TOOL_VERSION_pkg_config */
#ifndef MIN_TOOL_VERSION_pkg_config
#define MIN_TOOL_VERSION_pkg_config(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  29 || \
  (major1) == 0 && (major2) == 29 && (minor) <= 2)
#endif /* MIN_TOOL_VERSION_pkg_config */

/* tool runghc-8.6.5 */
#ifndef TOOL_VERSION_runghc
#define TOOL_VERSION_runghc "8.6.5"
#endif /* TOOL_VERSION_runghc */
#ifndef MIN_TOOL_VERSION_runghc
#define MIN_TOOL_VERSION_runghc(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  6 || \
  (major1) == 8 && (major2) == 6 && (minor) <= 5)
#endif /* MIN_TOOL_VERSION_runghc */

/* tool strip-2.29 */
#ifndef TOOL_VERSION_strip
#define TOOL_VERSION_strip "2.29"
#endif /* TOOL_VERSION_strip */
#ifndef MIN_TOOL_VERSION_strip
#define MIN_TOOL_VERSION_strip(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  29 || \
  (major1) == 2 && (major2) == 29 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_strip */

#ifndef CURRENT_PACKAGE_KEY
#define CURRENT_PACKAGE_KEY "ceph-0.0.1-IjLSOwf1IxhF1acqKTsPBi"
#endif /* CURRENT_PACKAGE_KEY */
#ifndef CURRENT_COMPONENT_ID
#define CURRENT_COMPONENT_ID "ceph-0.0.1-IjLSOwf1IxhF1acqKTsPBi"
#endif /* CURRENT_COMPONENT_ID */
#ifndef CURRENT_PACKAGE_VERSION
#define CURRENT_PACKAGE_VERSION "0.0.1"
#endif /* CURRENT_PACKAGE_VERSION */

#undef CURRENT_PACKAGE_KEY
#undef CURRENT_COMPONENT_ID
/* DO NOT EDIT: This file is automatically generated by Cabal */

/* package ceph-0.0.1 */
#ifndef VERSION_ceph
#define VERSION_ceph "0.0.1"
#endif /* VERSION_ceph */
#ifndef MIN_VERSION_ceph
#define MIN_VERSION_ceph(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  0 || \
  (major1) == 0 && (major2) == 0 && (minor) <= 1)
#endif /* MIN_VERSION_ceph */

/* package Euterpea-2.0.7 */
#ifndef VERSION_Euterpea
#define VERSION_Euterpea "2.0.7"
#endif /* VERSION_Euterpea */
#ifndef MIN_VERSION_Euterpea
#define MIN_VERSION_Euterpea(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  0 || \
  (major1) == 2 && (major2) == 0 && (minor) <= 7)
#endif /* MIN_VERSION_Euterpea */

/* package HCodecs-0.5.1 */
#ifndef VERSION_HCodecs
#define VERSION_HCodecs "0.5.1"
#endif /* VERSION_HCodecs */
#ifndef MIN_VERSION_HCodecs
#define MIN_VERSION_HCodecs(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  5 || \
  (major1) == 0 && (major2) == 5 && (minor) <= 1)
#endif /* MIN_VERSION_HCodecs */

/* package StateVar-1.1.1.1 */
#ifndef VERSION_StateVar
#define VERSION_StateVar "1.1.1.1"
#endif /* VERSION_StateVar */
#ifndef MIN_VERSION_StateVar
#define MIN_VERSION_StateVar(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  1 || \
  (major1) == 1 && (major2) == 1 && (minor) <= 1)
#endif /* MIN_VERSION_StateVar */

/* package adjunctions-4.4 */
#ifndef VERSION_adjunctions
#define VERSION_adjunctions "4.4"
#endif /* VERSION_adjunctions */
#ifndef MIN_VERSION_adjunctions
#define MIN_VERSION_adjunctions(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  4 || \
  (major1) == 4 && (major2) == 4 && (minor) <= 0)
#endif /* MIN_VERSION_adjunctions */

/* package aeson-1.4.4.0 */
#ifndef VERSION_aeson
#define VERSION_aeson "1.4.4.0"
#endif /* VERSION_aeson */
#ifndef MIN_VERSION_aeson
#define MIN_VERSION_aeson(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  4 || \
  (major1) == 1 && (major2) == 4 && (minor) <= 4)
#endif /* MIN_VERSION_aeson */

/* package apecs-0.7.1 */
#ifndef VERSION_apecs
#define VERSION_apecs "0.7.1"
#endif /* VERSION_apecs */
#ifndef MIN_VERSION_apecs
#define MIN_VERSION_apecs(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  7 || \
  (major1) == 0 && (major2) == 7 && (minor) <= 1)
#endif /* MIN_VERSION_apecs */

/* package base-4.12.0.0 */
#ifndef VERSION_base
#define VERSION_base "4.12.0.0"
#endif /* VERSION_base */
#ifndef MIN_VERSION_base
#define MIN_VERSION_base(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  12 || \
  (major1) == 4 && (major2) == 12 && (minor) <= 0)
#endif /* MIN_VERSION_base */

/* package bytestring-0.10.8.2 */
#ifndef VERSION_bytestring
#define VERSION_bytestring "0.10.8.2"
#endif /* VERSION_bytestring */
#ifndef MIN_VERSION_bytestring
#define MIN_VERSION_bytestring(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  10 || \
  (major1) == 0 && (major2) == 10 && (minor) <= 8)
#endif /* MIN_VERSION_bytestring */

/* package containers-0.5.11.0 */
#ifndef VERSION_containers
#define VERSION_containers "0.5.11.0"
#endif /* VERSION_containers */
#ifndef MIN_VERSION_containers
#define MIN_VERSION_containers(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  5 || \
  (major1) == 0 && (major2) == 5 && (minor) <= 11)
#endif /* MIN_VERSION_containers */

/* package directory-1.3.3.0 */
#ifndef VERSION_directory
#define VERSION_directory "1.3.3.0"
#endif /* VERSION_directory */
#ifndef MIN_VERSION_directory
#define MIN_VERSION_directory(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  3 || \
  (major1) == 1 && (major2) == 3 && (minor) <= 3)
#endif /* MIN_VERSION_directory */

/* package distributive-0.6 */
#ifndef VERSION_distributive
#define VERSION_distributive "0.6"
#endif /* VERSION_distributive */
#ifndef MIN_VERSION_distributive
#define MIN_VERSION_distributive(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  6 || \
  (major1) == 0 && (major2) == 6 && (minor) <= 0)
#endif /* MIN_VERSION_distributive */

/* package first-class-families-0.5.0.0 */
#ifndef VERSION_first_class_families
#define VERSION_first_class_families "0.5.0.0"
#endif /* VERSION_first_class_families */
#ifndef MIN_VERSION_first_class_families
#define MIN_VERSION_first_class_families(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  5 || \
  (major1) == 0 && (major2) == 5 && (minor) <= 0)
#endif /* MIN_VERSION_first_class_families */

/* package gloss-1.13.0.1 */
#ifndef VERSION_gloss
#define VERSION_gloss "1.13.0.1"
#endif /* VERSION_gloss */
#ifndef MIN_VERSION_gloss
#define MIN_VERSION_gloss(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  13 || \
  (major1) == 1 && (major2) == 13 && (minor) <= 0)
#endif /* MIN_VERSION_gloss */

/* package groups-0.4.1.0 */
#ifndef VERSION_groups
#define VERSION_groups "0.4.1.0"
#endif /* VERSION_groups */
#ifndef MIN_VERSION_groups
#define MIN_VERSION_groups(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  4 || \
  (major1) == 0 && (major2) == 4 && (minor) <= 1)
#endif /* MIN_VERSION_groups */

/* package lens-4.17.1 */
#ifndef VERSION_lens
#define VERSION_lens "4.17.1"
#endif /* VERSION_lens */
#ifndef MIN_VERSION_lens
#define MIN_VERSION_lens(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  17 || \
  (major1) == 4 && (major2) == 17 && (minor) <= 1)
#endif /* MIN_VERSION_lens */

/* package linear-1.20.9 */
#ifndef VERSION_linear
#define VERSION_linear "1.20.9"
#endif /* VERSION_linear */
#ifndef MIN_VERSION_linear
#define MIN_VERSION_linear(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  20 || \
  (major1) == 1 && (major2) == 20 && (minor) <= 9)
#endif /* MIN_VERSION_linear */

/* package mtl-2.2.2 */
#ifndef VERSION_mtl
#define VERSION_mtl "2.2.2"
#endif /* VERSION_mtl */
#ifndef MIN_VERSION_mtl
#define MIN_VERSION_mtl(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  2 || \
  (major1) == 2 && (major2) == 2 && (minor) <= 2)
#endif /* MIN_VERSION_mtl */

/* package optparse-applicative-0.14.3.0 */
#ifndef VERSION_optparse_applicative
#define VERSION_optparse_applicative "0.14.3.0"
#endif /* VERSION_optparse_applicative */
#ifndef MIN_VERSION_optparse_applicative
#define MIN_VERSION_optparse_applicative(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  14 || \
  (major1) == 0 && (major2) == 14 && (minor) <= 3)
#endif /* MIN_VERSION_optparse_applicative */

/* package random-1.1 */
#ifndef VERSION_random
#define VERSION_random "1.1"
#endif /* VERSION_random */
#ifndef MIN_VERSION_random
#define MIN_VERSION_random(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  1 || \
  (major1) == 1 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_random */

/* package safe-0.3.17 */
#ifndef VERSION_safe
#define VERSION_safe "0.3.17"
#endif /* VERSION_safe */
#ifndef MIN_VERSION_safe
#define MIN_VERSION_safe(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  3 || \
  (major1) == 0 && (major2) == 3 && (minor) <= 17)
#endif /* MIN_VERSION_safe */

/* package safe-exceptions-0.1.7.0 */
#ifndef VERSION_safe_exceptions
#define VERSION_safe_exceptions "0.1.7.0"
#endif /* VERSION_safe_exceptions */
#ifndef MIN_VERSION_safe_exceptions
#define MIN_VERSION_safe_exceptions(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 7)
#endif /* MIN_VERSION_safe_exceptions */

/* package sdl2-2.4.1.0 */
#ifndef VERSION_sdl2
#define VERSION_sdl2 "2.4.1.0"
#endif /* VERSION_sdl2 */
#ifndef MIN_VERSION_sdl2
#define MIN_VERSION_sdl2(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  4 || \
  (major1) == 2 && (major2) == 4 && (minor) <= 1)
#endif /* MIN_VERSION_sdl2 */

/* package sdl2-mixer-1.1.0 */
#ifndef VERSION_sdl2_mixer
#define VERSION_sdl2_mixer "1.1.0"
#endif /* VERSION_sdl2_mixer */
#ifndef MIN_VERSION_sdl2_mixer
#define MIN_VERSION_sdl2_mixer(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  1 || \
  (major1) == 1 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_sdl2_mixer */

/* package sdl2-ttf-2.1.0 */
#ifndef VERSION_sdl2_ttf
#define VERSION_sdl2_ttf "2.1.0"
#endif /* VERSION_sdl2_ttf */
#ifndef MIN_VERSION_sdl2_ttf
#define MIN_VERSION_sdl2_ttf(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  1 || \
  (major1) == 2 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_sdl2_ttf */

/* package singletons-2.5.1 */
#ifndef VERSION_singletons
#define VERSION_singletons "2.5.1"
#endif /* VERSION_singletons */
#ifndef MIN_VERSION_singletons
#define MIN_VERSION_singletons(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  5 || \
  (major1) == 2 && (major2) == 5 && (minor) <= 1)
#endif /* MIN_VERSION_singletons */

/* package template-haskell-2.14.0.0 */
#ifndef VERSION_template_haskell
#define VERSION_template_haskell "2.14.0.0"
#endif /* VERSION_template_haskell */
#ifndef MIN_VERSION_template_haskell
#define MIN_VERSION_template_haskell(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  14 || \
  (major1) == 2 && (major2) == 14 && (minor) <= 0)
#endif /* MIN_VERSION_template_haskell */

/* package text-1.2.3.1 */
#ifndef VERSION_text
#define VERSION_text "1.2.3.1"
#endif /* VERSION_text */
#ifndef MIN_VERSION_text
#define MIN_VERSION_text(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  2 || \
  (major1) == 1 && (major2) == 2 && (minor) <= 3)
#endif /* MIN_VERSION_text */

/* package text-conversions-0.3.0 */
#ifndef VERSION_text_conversions
#define VERSION_text_conversions "0.3.0"
#endif /* VERSION_text_conversions */
#ifndef MIN_VERSION_text_conversions
#define MIN_VERSION_text_conversions(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  3 || \
  (major1) == 0 && (major2) == 3 && (minor) <= 0)
#endif /* MIN_VERSION_text_conversions */

/* package time-1.8.0.2 */
#ifndef VERSION_time
#define VERSION_time "1.8.0.2"
#endif /* VERSION_time */
#ifndef MIN_VERSION_time
#define MIN_VERSION_time(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  8 || \
  (major1) == 1 && (major2) == 8 && (minor) <= 0)
#endif /* MIN_VERSION_time */

/* package vector-0.12.0.3 */
#ifndef VERSION_vector
#define VERSION_vector "0.12.0.3"
#endif /* VERSION_vector */
#ifndef MIN_VERSION_vector
#define MIN_VERSION_vector(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  12 || \
  (major1) == 0 && (major2) == 12 && (minor) <= 0)
#endif /* MIN_VERSION_vector */

/* tool gcc-7.2.0 */
#ifndef TOOL_VERSION_gcc
#define TOOL_VERSION_gcc "7.2.0"
#endif /* TOOL_VERSION_gcc */
#ifndef MIN_TOOL_VERSION_gcc
#define MIN_TOOL_VERSION_gcc(major1,major2,minor) (\
  (major1) <  7 || \
  (major1) == 7 && (major2) <  2 || \
  (major1) == 7 && (major2) == 2 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_gcc */

/* tool ghc-8.6.5 */
#ifndef TOOL_VERSION_ghc
#define TOOL_VERSION_ghc "8.6.5"
#endif /* TOOL_VERSION_ghc */
#ifndef MIN_TOOL_VERSION_ghc
#define MIN_TOOL_VERSION_ghc(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  6 || \
  (major1) == 8 && (major2) == 6 && (minor) <= 5)
#endif /* MIN_TOOL_VERSION_ghc */

/* tool ghc-pkg-8.6.5 */
#ifndef TOOL_VERSION_ghc_pkg
#define TOOL_VERSION_ghc_pkg "8.6.5"
#endif /* TOOL_VERSION_ghc_pkg */
#ifndef MIN_TOOL_VERSION_ghc_pkg
#define MIN_TOOL_VERSION_ghc_pkg(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  6 || \
  (major1) == 8 && (major2) == 6 && (minor) <= 5)
#endif /* MIN_TOOL_VERSION_ghc_pkg */

/* tool haddock-2.22.0 */
#ifndef TOOL_VERSION_haddock
#define TOOL_VERSION_haddock "2.22.0"
#endif /* TOOL_VERSION_haddock */
#ifndef MIN_TOOL_VERSION_haddock
#define MIN_TOOL_VERSION_haddock(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  22 || \
  (major1) == 2 && (major2) == 22 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_haddock */

/* tool hpc-0.67 */
#ifndef TOOL_VERSION_hpc
#define TOOL_VERSION_hpc "0.67"
#endif /* TOOL_VERSION_hpc */
#ifndef MIN_TOOL_VERSION_hpc
#define MIN_TOOL_VERSION_hpc(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  67 || \
  (major1) == 0 && (major2) == 67 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_hpc */

/* tool hsc2hs-0.68.5 */
#ifndef TOOL_VERSION_hsc2hs
#define TOOL_VERSION_hsc2hs "0.68.5"
#endif /* TOOL_VERSION_hsc2hs */
#ifndef MIN_TOOL_VERSION_hsc2hs
#define MIN_TOOL_VERSION_hsc2hs(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 5)
#endif /* MIN_TOOL_VERSION_hsc2hs */

/* tool pkg-config-0.29.2 */
#ifndef TOOL_VERSION_pkg_config
#define TOOL_VERSION_pkg_config "0.29.2"
#endif /* TOOL_VERSION_pkg_config */
#ifndef MIN_TOOL_VERSION_pkg_config
#define MIN_TOOL_VERSION_pkg_config(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  29 || \
  (major1) == 0 && (major2) == 29 && (minor) <= 2)
#endif /* MIN_TOOL_VERSION_pkg_config */

/* tool runghc-8.6.5 */
#ifndef TOOL_VERSION_runghc
#define TOOL_VERSION_runghc "8.6.5"
#endif /* TOOL_VERSION_runghc */
#ifndef MIN_TOOL_VERSION_runghc
#define MIN_TOOL_VERSION_runghc(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  6 || \
  (major1) == 8 && (major2) == 6 && (minor) <= 5)
#endif /* MIN_TOOL_VERSION_runghc */

/* tool strip-2.29 */
#ifndef TOOL_VERSION_strip
#define TOOL_VERSION_strip "2.29"
#endif /* TOOL_VERSION_strip */
#ifndef MIN_TOOL_VERSION_strip
#define MIN_TOOL_VERSION_strip(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  29 || \
  (major1) == 2 && (major2) == 29 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_strip */

#ifndef CURRENT_COMPONENT_ID
#define CURRENT_COMPONENT_ID "ceph-0.0.1-9XWLcSYvACVKpDWho6M1J4-ceph"
#endif /* CURRENT_COMPONENT_ID */
#ifndef CURRENT_PACKAGE_VERSION
#define CURRENT_PACKAGE_VERSION "0.0.1"
#endif /* CURRENT_PACKAGE_VERSION */

#undef CURRENT_PACKAGE_KEY
#undef CURRENT_COMPONENT_ID
