resolver: lts-9.11
packages:
- .
- apecs-physics-gloss
- examples
- seffyball
extra-deps:
  - apecs-0.2.4.7
  - gloss-juicy-0.2.2
#  - SDL-mixer-0.6.2.0
  - sdl2-mixer-1.1.0
flags: {}
extra-package-dbs: []
